Task2
hopenz/FinBot pull request #18
Opened 2024-11-17 09:54 UTC by hopenz

### Задача №2
1. Интегрировать бота с Google Sheets API:
   * Настроить аутентификацию и авторизацию для доступа к Google Sheets
   * Реализовать функции для чтения и записи данных в Google Sheets

2. tg id и ссылки на гугл-таблицу будут храниться в оперативной памяти.
3. Возможность выбора пользователем места хранения данных.

При старте бота должен быть предоставлен выбор пользователю, где он хочет хранить данные (оперативная память
/ гугл-таблица). Если он выбирает взаимодействовать с гугл таблицей, то бот попросит ссылку на созданную 
пользователем гугл таблицу и будет хранить данные в ней, в противном случае - все данные будут храниться 
в оперативной память. Также должна быть реализована возможность поменять место хранения (/changeDB), 
с переносом имеющихся данных.

Создавать таблицу пользователю нужно будет только один раз, дальше если он будет несколько раз менять варианты хранения, 
то будет использоваться ранее созданная таблица.

На данном этапе после добавления операции в доходы/расходы в личной гугл-таблице пользователя
должны появляться данные о введенных транзакциях. (Для варианта хранения: гугл таблицы)

Баланс будет высчитываться по формуле в гугл-таблице [Сумма доходов - сумма расходов] 
и храниться в ячейке этой таблицы. (Для варианта хранения: гугл таблицы)

2024-11-17 09:58 UTC, hopenz commented
Не бейте :)
Мы не нашли другого способа передать обработку исключения в ExceptionHandler, так как при выбрасывания исключения исключение попадает в хендлеры библиотеки. И в дальнейшем его обработать не получается, так как оно оборачивается в кастомный exception библиотеки.

2024-11-17 14:08 UTC, YaEtoTui commented on src/main/java/ru/naumen/bot/exception/BotControllerAdvice.java
> +public class BotControllerAdvice {
все таки это advice. На него отдельно package надо, а то в exception как то не так-то)

2024-11-17 14:10 UTC, YaEtoTui commented on src/main/java/ru/naumen/bot/processor/CallbackQueryProcessor.java
> +        DataType dataType = data.equals("Гугл-таблица")
Вот ты проверяешь на строку, но такой вопрос... А если что-то поменяется, и поменяется сообщение, которое придет. Не думаете как-то их хранить в виде констант либо enum например?

2024-11-17 14:11 UTC, YaEtoTui commented on src/main/java/ru/naumen/bot/processor/CallbackQueryProcessor.java
> +        if (data.equals("Гугл-таблица")) {
аналогично выше комменту

2024-11-17 14:24 UTC, YaEtoTui commented
2-ое задание принято

2024-11-17 15:07 UTC, hopenz commented on src/main/java/ru/naumen/bot/exception/BotControllerAdvice.java
> +public class BotControllerAdvice {
Перенесла в отдельный пакет

2024-11-17 15:08 UTC, hopenz commented on src/main/java/ru/naumen/bot/processor/CallbackQueryProcessor.java
> +        DataType dataType = data.equals("Гугл-таблица")
Кнопки инлайн клавиатуры вынесены в enum

2024-11-17 15:08 UTC, hopenz commented on src/main/java/ru/naumen/bot/processor/CallbackQueryProcessor.java
> +        if (data.equals("Гугл-таблица")) {
Кнопки инлайн клавиатуры вынесены в enum

2024-11-17 15:10 UTC, hopenz commented
Замечания исправлены

2024-11-23 17:42 UTC, vpyzhyanov commented
> Не бейте :) Мы не нашли другого способа передать обработку исключения в ExceptionHandler, так как при выбрасывания исключения исключение попадает в хендлеры библиотеки. И в дальнейшем его обработать не получается, так как оно оборачивается в кастомный exception библиотеки.

Всё-таки пришлось бить) Парочка лёгких ударов сделала код лучше))

Правда лучше бы обработка исключения была в методе `processUpdate`. Всё-таки именно он отвечает за обработку команды/кнопки/и пр. 

P.S. Небольшая коллективная безответственность

2024-11-23 20:14 UTC, vpyzhyanov requested changes
Очень много тёмной стороны. Надо выбираться

2024-11-23 20:14 UTC, vpyzhyanov commented on pom.xml
> +            <!--Зависимость для решения уязвимости spring-boot-starter-data-web-->
молодцы!

2024-11-23 20:14 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/advice/BotControllerAdvice.java
> +public class BotControllerAdvice {
Кажется я понял за что вы просили не бить. Но бить всё-таки придётся((( Хотя бы эта просьба значит, что вы понимаете существование проблемы, но, кажется, не понимаете в чём именно она заключается. Иначе вы бы её решили или задали бы конкретный вопрос. А проблема именно в тёмной стороне ООП.

1. Начнём с простого. Название и описание из разных непересекающихся миров. Название раздаёт советы для BotController, а описание рассказываем нам про какой-то обработчик исключений
2. Связь с BotController: Если такая связь и вправду есть, то класс должен располагаться в том же пакете, где лежит BotController.
3. Связь с BotController 2: Мы видим аннотацию `@Lazy`. Такая аннотация обычно говорит о наличии проблемы в архитектуре, т.е. обычно она ставится для разрешения циклической зависимости. Точно ли она нужна в этом случае? Конечно же нет, она тут сделана искусственно. Но об этом позже.
4. Связь с BotController 3: Это класс вызывается из BotController, и внутри себя обращается к BotController. Возникает вопрос "Почему BotController такой беспомощный, что сам сделать ничего не может?". Добро пожаловать в коллективную безответственность.
5. Идея выносить обработку исключения в отдельный класс кажется сомнительной, т.к. всё равно основную работу делает не он, а botController и userService. Но тогда надо будет тащить зависимость userService в TelegramBotController и тогда их станет слишком много. И тут самое время задуматься о рефакторинге, раз уж изначально не получилось применить ООП в классе TelegramBotController.

Что мы имеем: зашли в тупик в тёмного переулке и не можете найти выход. И не мудрено, из тёмной стороны выбираться действительно сложно, ничего же не видно))) Но тут выбраться всё-таки можно. Но не сразу, а поэтапно:

1. Выкидываем класс BotControllerAdvice, т.к. он безответственный
2. Переносим обработку GoogleSheetsException туда, где она на самом деле начинает обрабатываться, т.е. в TelegramBotController. Циклическую зависимость мы победили.
3. Обработку исключения переносим в метод processUpdate, ибо не надо лезть с лишней обработкой в настройку бота
4. В контроллере появилась ещё одна зависимость от UserService. Теперь тут аж 6 аргументов в конструкторе. Это точно тёмная сторона, её надо решать.
5. Самое время применить ниспадающее программирование

Оставлю пока вам возможность подумать как эту проблему решить. Если что, подскажу как.

2024-11-23 20:14 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/exception/GoogleSheetsException.java
> +    public String getMessageForBot() {
хмм... подозрительно. Интересно кто пишет сообщения пользователю в исключения. Высока вероятность, что я найду коллективную безответственность.

P.S. если что важно не то, что исключение передаёт текст сообщения для пользователя, а в том кто её отправляет.

2024-11-23 20:14 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/data/dao/googleSheets/GoogleSheetsIncomeDao.java
> +            throw new GoogleSheetsException(e.getMessage(), chatId, "Ошибка получения доходов");
Вот, нашёл! Добро пожаловать в коллективную безответственность. С какой стати какой-то DAO общается с пользователем?! Он не должен так делать! Вообще-то он вообще не должен знать о существовании телеграмм бота и о том как пользователь с ним общается.

Чтобы облегчить поиск решения проблемы рекомендую вам применить полиморфизм. Создайте своё **проверяемое** исключение и пропишите его в IncomeDao. GoogleSheetsException можете наследовать от него.

И на самом деле GoogleSheetsException должен обрабатываться не в TelegramBotController, а где-то в другом месте. Но об этом я уже писал ранее.

Потеряли стек! Видимо хотите осложнить себе анализ ошибки.

2024-11-23 20:14 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/client/GoogleSheetsClient.java
> +        String credentialsPath = "src/main/resources/credentials.json";
в константу

2024-11-23 20:14 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/client/GoogleSheetsClient.java
> +        FileInputStream serviceAccountStream = new FileInputStream(credentialsPath);
самое время учиться работать с потоками ввода вывода. Это база

2024-11-23 20:14 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/controller/BotController.java
> +    void sendMessageWithInlineKeyboard(String message, long chatId, List<String> buttons);
можно было сделать перегрузку метода `sendMessage` и новое название не придумывать. Смысл ведь один и тот же

2024-11-23 20:14 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/controller/BotController.java
> +    void sendAnswerCallbackQuery(String message, String callbackQueryId);
чем отличается отправка ответа от отправки сообщения?

2024-11-23 20:14 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/controller/telegram/TelegramBotController.java
> +                logger.error("[Google Sheets exception] :: Message: {}.", exception.getMessage());
стек потеряли

2024-11-23 20:14 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/controller/telegram/TelegramBotController.java
> +            callbackQueryProcessor.processCallbackQuery(callbackQuery.data(),
вам не кажется, что процессоров стало слишком много?

2024-11-23 20:14 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/controller/telegram/TelegramBotController.java
>          telegramBot.execute(new SendMessage(chatId, message));
теперь этот метод частично дублирует sendMessageWithInlineKeyboard

2024-11-23 20:14 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/data/dao/BalanceDao.java
> +     * @return баланс пользователя
не надо дублировать информацию. Это поле нужно не для этого

2024-11-23 20:14 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/data/dao/DaoProvider.java
> +                       GoogleSheetsBalanceDao googleSheetsBalanceDao) {
тут тёмная сторона очевидна. Какая она?

2024-11-23 20:14 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/data/dao/DaoProvider.java
> +    public InMemoryBalanceDao getInMemoryBalanceDao() {
странно тут видеть такой метод. Ну прям очень странно. А всё потому, что он обесценивает весь этот класс (DaoProvider). Какой смысл в нём, если вы всё равно обращаетесь к конкретной реализации?!

2024-11-23 20:14 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/service/DatabaseService.java
> +        daoProvider.getInMemoryBalanceDao().setBalance(chatId, 0.0);
провайдер выкидываем и указываем нужный ДАО явно, без лишних посредников.

2024-11-23 20:14 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/service/DatabaseService.java
> +    public DatabaseService(DaoProvider daoProvider, @Lazy UserService userService, IncomeService incomeService,
опять циклическая зависимость. Давайте её уберём

2024-11-23 20:14 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/service/DatabaseService.java
> +                           ExpenseService expenseService, BalanceService balanceService, GoogleSheetsDao googleSheetsDao) {
опять тёмная сторона! Да ещё и вместе определены и сервисы и ДАО. Не бывает такого? Опять заблудились во мраке?

Пока не буду ничего подсказывать, попробуйте пока сами решить эту проблему

2024-11-23 20:14 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/processor/MessageBotProcessor.java
> +            databaseService.createGoogleSheetsDB(chatId);
яркий признак излишнего разделения ответственности когда в коде один и тот же объект вызывается 2 раза подряд. В данном случае метод changeDB вполне может сам создать таблицу, если её нет.

2024-11-23 20:14 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/service/UserService.java
> +    private final InMemoryUserDao userDao;
зачем писать InMemory?  Тут вы зашиваетесь на определённую реализацию и ограничиваете себя в расширении функционала.

2024-11-23 20:14 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/service/UserService.java
> +    public UserService(InMemoryUserDao userDao, @Lazy DatabaseService databaseService) {
опять циклическая зависимость. Их становится крайне много. Проблема всё серьёзнее и серьёзнее

2024-11-23 20:14 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/service/UserService.java
> +        String googleSheetId = link.substring(link.indexOf("/d/") + 3, link.indexOf("/edit"));
никаких магических чисел! В константу её

2024-11-23 20:14 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/utils/GoogleSheetsConverter.java
> +        if (data == null) return List.of();
Мастера однострочного программирования на рынке не катируются

2024-11-23 20:14 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/utils/GoogleSheetsConverter.java
> +        if (data == null) return List.of();
аналогично

2024-11-23 20:14 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/utils/GoogleSheetsConverter.java
> +        if (data == null) return 0.0;
И тут

2024-11-23 20:14 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/controller/telegram/TelegramBotController.java
> +                botControllerAdvice.handleGoogleSheetsException(exception);
нет тестов на логику TelegramBotController.

На самом деле и не должно быть, если сделать всё правильно. Но тут сделано неправильно. Логики тут быть вообще не должно. Ну а пока она есть, буду требовать либо убрать логику, либо написать тест. Лучше первое.

2024-11-23 20:15 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/exception/BotControllerAdvice.java
> +public class BotControllerAdvice {
Служебный класс для BotController не может находится в пакете, отличном от того, где находится сам BotController

2024-11-26 10:54 UTC, hopenz commented on src/main/java/ru/naumen/bot/client/GoogleSheetsClient.java
> +        String credentialsPath = "src/main/resources/credentials.json";
Вынесла в константу

2024-11-26 10:55 UTC, LARCH1K commented on src/main/java/ru/naumen/bot/controller/BotController.java
> +    void sendMessageWithInlineKeyboard(String message, long chatId, List<String> buttons);
Перегрузка метода сделана

2024-11-26 10:55 UTC, hopenz commented on src/main/java/ru/naumen/bot/client/GoogleSheetsClient.java
> +        FileInputStream serviceAccountStream = new FileInputStream(credentialsPath);
Обернули в try-with-resources, чтобы закрыть потоки

2024-11-26 10:57 UTC, LARCH1K commented on src/main/java/ru/naumen/bot/controller/BotController.java
> +    void sendAnswerCallbackQuery(String message, String callbackQueryId);
Переименовали. Здесь сообщение не обычное, а всплывающее  поэтому метод теперь называется `sendPopUpMessage()`

2024-11-26 10:58 UTC, hopenz commented on src/main/java/ru/naumen/bot/data/dao/DaoProvider.java
> +                       GoogleSheetsBalanceDao googleSheetsBalanceDao) {
Была темная сторона "Большое количество аргументов",  сейчас разделили аргументы на две группы: InMemoryDaoGroup и GoogleSheetsDaoGroup

2024-11-26 10:59 UTC, LARCH1K commented on src/main/java/ru/naumen/bot/controller/telegram/TelegramBotController.java
>          telegramBot.execute(new SendMessage(chatId, message));
Метод теперь вызывает перегруженный метод

2024-11-26 10:59 UTC, LARCH1K commented on src/main/java/ru/naumen/bot/data/dao/BalanceDao.java
> +     * @return баланс пользователя
Убрали

2024-11-26 11:02 UTC, LARCH1K commented on src/main/java/ru/naumen/bot/data/dao/DaoProvider.java
> +    public InMemoryBalanceDao getInMemoryBalanceDao() {
Убрали

2024-11-26 11:03 UTC, LARCH1K commented on src/main/java/ru/naumen/bot/service/DatabaseService.java
> +        daoProvider.getInMemoryBalanceDao().setBalance(chatId, 0.0);
Метод убран целиком

2024-11-26 11:03 UTC, LARCH1K commented on src/main/java/ru/naumen/bot/service/DatabaseService.java
> +    public DatabaseService(DaoProvider daoProvider, @Lazy UserService userService, IncomeService incomeService,
Убрали

2024-11-26 11:04 UTC, LARCH1K commented on src/main/java/ru/naumen/bot/service/DatabaseService.java
> +                           ExpenseService expenseService, BalanceService balanceService, GoogleSheetsDao googleSheetsDao) {
Теперь сервисы работают либо только с сервисами, либо только с DAO

2024-11-26 11:04 UTC, hopenz commented on src/main/java/ru/naumen/bot/processor/MessageBotProcessor.java
> +            databaseService.createGoogleSheetsDB(chatId);
Инициализация таблицы перенесена в changeDB

2024-11-26 11:05 UTC, hopenz commented on src/main/java/ru/naumen/bot/service/UserService.java
> +        String googleSheetId = link.substring(link.indexOf("/d/") + 3, link.indexOf("/edit"));
Вынесли в константы

2024-11-26 11:05 UTC, hopenz commented on src/main/java/ru/naumen/bot/utils/GoogleSheetsConverter.java
> +        if (data == null) return List.of();
Убрали однострочное программирование

2024-11-26 11:06 UTC, hopenz commented on src/main/java/ru/naumen/bot/utils/GoogleSheetsConverter.java
> +        if (data == null) return List.of();
Убрали однострочное программирование

2024-11-26 11:06 UTC, hopenz commented on src/main/java/ru/naumen/bot/utils/GoogleSheetsConverter.java
> +        if (data == null) return 0.0;
Убрали однострочное программирование

2024-11-26 11:07 UTC, LARCH1K commented on src/main/java/ru/naumen/bot/service/UserService.java
> +    private final InMemoryUserDao userDao;
Мы в целом убрали интерфейс UserDao, т.к наш проект не предполагает хранение данных о пользователях не в памяти, поэтому и избавились от лишнего интерфейса

2024-11-26 11:07 UTC, hopenz commented on src/main/java/ru/naumen/bot/service/UserService.java
> +    public UserService(InMemoryUserDao userDao, @Lazy DatabaseService databaseService) {
Исправлено

2024-11-26 11:08 UTC, hopenz commented on src/main/java/ru/naumen/bot/controller/telegram/TelegramBotController.java
> +                botControllerAdvice.handleGoogleSheetsException(exception);
Логика убрана

2024-11-26 11:08 UTC, LARCH1K commented on src/main/java/ru/naumen/bot/exception/BotControllerAdvice.java
> +public class BotControllerAdvice {
Класса больше нет

2024-11-26 11:09 UTC, LARCH1K commented on src/main/java/ru/naumen/bot/exception/GoogleSheetsException.java
> +    public String getMessageForBot() {
В исключение больше не передаётся сообщение для пользователя

2024-11-26 11:10 UTC, LARCH1K commented on src/main/java/ru/naumen/bot/advice/BotControllerAdvice.java
> +public class BotControllerAdvice {
Обработка исключений перенесена в процессоры

2024-11-26 11:33 UTC, LARCH1K commented on src/main/java/ru/naumen/bot/data/dao/googleSheets/GoogleSheetsIncomeDao.java
> +            throw new GoogleSheetsException(e.getMessage(), chatId, "Ошибка получения доходов");
Возникли сложности и не получилось всё сделать, как вы писали. Не вышло применить проверяемое исключение, так как в случае проверяемого исключения  нужно:
- Либо обработать его в DAO, что сделать нельзя, т.к. нужно отправлять сообщение пользователю
- Либо пробрасывать его дальше, но в этом случае придётся менять сигнатуру интерфейсов DAO, что тоже показалось не правильным

Отлов исключения мы перенесли в процессоры, т.к. они отвечают за отправку ответа пользователю, что нам и нужно сделать в случае возникновения исключения. 
Обработка исключения вынесена в отдельный класс `GoogleSheetsExceptionHandler` (Не знаю насколько правильно передавать в метод `handleGoogleSheetsException(GoogleSheetsException exception, long chatId)` chatId, но оставил так, чтобы не писать лишней информации в исключение из dao)

2024-11-26 11:33 UTC, LARCH1K commented on src/main/java/ru/naumen/bot/controller/telegram/TelegramBotController.java
> +                logger.error("[Google Sheets exception] :: Message: {}.", exception.getMessage());
Везде в лог добавили

2024-11-26 11:40 UTC, LARCH1K commented on src/main/java/ru/naumen/bot/controller/telegram/TelegramBotController.java
> +            callbackQueryProcessor.processCallbackQuery(callbackQuery.data(),
Не придумали другого решения обработки сообщений разного формата (Разве что сократить число процессоров,  вынеся обработку команд и простых сообщений в один обработчик текстовых сообщений)
Также была мысль сделать интерфейс для процессоров, но тогда придётся на обработку передавать update (т.к. информация может приходить в разном формате), и в этом случае мы будем завязываться на конкретной библиотеке

2024-11-26 13:37 UTC, LARCH1K commented on src/main/java/ru/naumen/bot/data/dao/googleSheets/GoogleSheetsIncomeDao.java
> +            throw new GoogleSheetsException(e.getMessage(), chatId, "Ошибка получения доходов");
Update: во время написания предыдущего комментария я понял о чём вы писали.
Создан проверяемый `DaoException`, `GoogleSheetsException` наследуется от него.
Также в `CommandBotProcessor` и `MessageBotProcessor` вынес сервисы для работы с финансами в один фасадный сервис, для уменьшения количества полей

2024-11-26 13:53 UTC, LARCH1K commented
Замечания исправлены, но есть неуверенность в обработке исключения. 
Не совсем понятно как её лучше реализовать (например, под каждый наследник `DaoException` создавать свой класс обработчик или лучше сделать один с методами под разную реализацию, что сразу не подходит под SOLID. Также не совсем ясно как лучше отлавливать `DaoException` и его наследников)

2024-11-28 19:54 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/advice/BotControllerAdvice.java
> +public class BotControllerAdvice {
Уже стало заметно лучше. Вынесли в отдельный обработчик `GoogleSheetsExceptionHandler` и обработали в разных командах.

Вот только это не идеальное решение, т.к. это просто переносит тёмную сторону из одного класса в другой. Или даже несколько.

![image](https://github.com/user-attachments/assets/32def2f2-a276-4708-8be2-ba628a7efa58)

Идеальное решение - было сделать из метода `ru.naumen.bot.controller.telegram.TelegramBotController#processUpdate` отдельный класс. Он вполне достоин быть отдельным классом с отдельной ответственностью. Вот только вы не можете туда передать Update, вам понадобится создать свой класс "Сообщение" и добавить туда всё что нужно.

С другой стороны в вашем решении есть обработка исключений в каждой команде - это хорошо. Но этим вполне можно пожертвовать ради общей обработки исключения.

Надеюсь, что вы в 3 задаче пойдёте дальше и примените больше ООП для обработки команд от пользователя.

2024-11-28 20:05 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/data/dao/googleSheets/GoogleSheetsIncomeDao.java
> +            throw new GoogleSheetsException(e.getMessage(), chatId, "Ошибка получения доходов");
> Также в `CommandBotProcessor` и `MessageBotProcessor` вынес сервисы для работы с финансами в один фасадный сервис, для уменьшения количества полей

ну ё-маё. Вы правда думаете, что это решает проблему? Я же рассказывал, что если так делать, то проблема никуда не исчезает, а просто скрывается. Зато количество связей увеличилось. Преимуществ вы никаких не получаете. Убирайте их! Это ещё большее зло. Дажа сама фраза "фасадный сервис" вызывает недоумение, что-то типа "сервис для сервиса"

У классов CommandBotProcessor и MessageBotProcessor и без этого слишком много зависимостей. Эту проблему надо решать! Посмотрю как вы решите её в 3 задаче, тогда сразу будет понятно познали ли вы ООП.

2024-11-28 20:06 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/client/GoogleSheetsClient.java
> +        String credentialsPath = "src/main/resources/credentials.json";
Константы именуются особым образом `CREDENTIALS_PATH`

2024-11-28 20:07 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/client/GoogleSheetsClient.java
> +        FileInputStream serviceAccountStream = new FileInputStream(credentialsPath);
Вот теперь правильно

2024-11-28 20:08 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/controller/BotController.java
> +    void sendAnswerCallbackQuery(String message, String callbackQueryId);
вот, теперь понятно. Правильный нейминг и правильное описание убирают лишние вопросы

2024-11-28 20:09 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/controller/telegram/TelegramBotController.java
> +            callbackQueryProcessor.processCallbackQuery(callbackQuery.data(),
Никто не мешает создать свой класс "сообщение" и добавить туда всё что нужно.

2024-11-28 20:11 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/data/dao/DaoProvider.java
> +                       GoogleSheetsBalanceDao googleSheetsBalanceDao) {
та же проблема. Ничего не изменилось, тёмная сторона как была, так и осталась, но стала ещё темнее и страшнее. Группировка делает только хуже, а код становится сложнее.

2024-11-28 20:20 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/service/UserService.java
> +        String googleSheetId = link.substring(link.indexOf("/d/") + 3, link.indexOf("/edit"));
А вы понимаете, что число может состоять не из одного символа?

2024-11-28 20:21 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/utils/GoogleSheetsConverter.java
> +        if (data == null) return List.of();
зато остальные строчки сделали очень длинными(((

2024-11-28 20:23 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/controller/telegram/TelegramBotController.java
> +                botControllerAdvice.handleGoogleSheetsException(exception);
на самом деле логика в классе TelegramBotController всё ещё осталась, просто она сосредоточена в методе `processUpdate`

2024-11-28 20:30 UTC, vpyzhyanov requested changes

2024-11-28 20:30 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/data/dao/DaoProvider.java
> +        return inMemoryDaoGroup.getInMemoryUserDao().getDataType(chatId).equals(DataType.IN_MEMORY)
как-то я не сразу заметил ещё одну очень тёмную сторону. Перегруз по ответственности. Каким-то образом inMemoryUserDao отвечает за тип хранения данных. Ключевое слово "**inMemory**".

В общем источник хранения информации должен определяться каким-то третьим лицом. А то это всё-равно, что самому себе зарплату начислять.

2024-11-28 20:30 UTC, vpyzhyanov commented
Оценка за Git - 3 балла.

2024-11-29 12:20 UTC, hopenz commented on src/main/java/ru/naumen/bot/client/GoogleSheetsClient.java
> +        String credentialsPath = "src/main/resources/credentials.json";
Исправили

2024-11-29 12:21 UTC, hopenz commented on src/main/java/ru/naumen/bot/service/UserService.java
> +        String googleSheetId = link.substring(link.indexOf("/d/") + 3, link.indexOf("/edit"));
Обговорили этот момент на паре, всё остается как есть

2024-11-29 12:22 UTC, hopenz commented on src/main/java/ru/naumen/bot/utils/GoogleSheetsConverter.java
> +        if (data == null) return List.of();
Исправили

2024-11-29 12:25 UTC, hopenz commented on src/main/java/ru/naumen/bot/data/dao/DaoProvider.java
> +        return inMemoryDaoGroup.getInMemoryUserDao().getDataType(chatId).equals(DataType.IN_MEMORY)
Переименовали в "UserDao", вынесли в пакет dao

2024-11-29 12:39 UTC, hopenz commented
Исправили замечания, не требующие изменения архитектуры.
Перед выполнением 3 задачи исправим оставшиеся замечания, чтобы отображались изменения.

2024-11-29 12:39 UTC, merged