Task1
hopenz/FinBot pull request #9
Opened 2024-10-21 09:39 UTC by LARCH1K

# Проект: Telegram-bot для ведения личных финансов

## Команда: Петрушина Надежда, Овчинников Никита

### Задача №1
Реализовать скелет телеграмм-бота. Бот должен уметь:
* Идентифицировать пользователя (по tg id)
* Обеспечить возможность работы нескольких пользователей одновременно
* Показать справку по работе бота (/help)
* Записывать расходы ( - <Сумма> <Наименование> )
* Записывать доходы ( + <Сумма> <Наименование> )
* Показывать баланс (/balance)
* Показать список расходов (/expenses)
* Показать список доходов (/income)

В данной задаче не будет интеграции с Гугл-таблицами,
вместо этого будет реализация БД в оперативной памяти.

2024-10-22 13:42 UTC, YaEtoTui commented on bot/src/main/java/ru/naumen/bot/configuration/ApplicationConfig.java
> +) {
у нас не С#. Это не ошибка а ремарка, форматируем вот так -> "String telegramToken) {"

2024-10-22 13:46 UTC, YaEtoTui commented on bot/src/main/java/ru/naumen/bot/data/dao/inMemory/InMemoryBalanceDao.java
> +        return usersBalance.get(chatId);
Хм. возможно вы предусмотрели, но а если баланса нет в Map, то get() вызовется с ошибкой. Тогда уж лучше getOrDefault. он отдаст либо из Map, либо default value. Почему я его вспомнил, а потому что у вас Double, а не double. То есть вы подразумеваете такое в теории

2024-10-22 13:50 UTC, YaEtoTui commented on bot/src/main/java/ru/naumen/bot/data/dao/inMemory/InMemoryBalanceDao.java
> +        return usersBalance.get(chatId);
лучше мне кажется getOrDefault тут, так как тут ладно если null. а если вы вызываете в BalanceService, то там возвращает из Double -> double. Мне кажется в будущем можете получить баг, так что лучше getOrDefault(), а там вставьте 0 как дефолт, как бы решите будущую проблему, на мой взгляд

2024-10-26 14:56 UTC, LARCH1K commented on bot/src/main/java/ru/naumen/bot/configuration/ApplicationConfig.java
> +) {
Учтём и исправим

2024-10-26 14:58 UTC, LARCH1K commented on bot/src/main/java/ru/naumen/bot/data/dao/inMemory/InMemoryBalanceDao.java
> +        return usersBalance.get(chatId);
Согласен, в дальнейшем исправим

2024-10-30 18:05 UTC, vpyzhyanov commented on bot/src/main/java/ru/naumen/bot/configuration/ApplicationConfig.java
> +) {
Ребята, замечания нужны, не для красоты и не "для вида", а чтобы их **исправлять**

2024-10-30 18:06 UTC, vpyzhyanov commented on bot/src/main/java/ru/naumen/bot/data/dao/inMemory/InMemoryBalanceDao.java
> +        return usersBalance.get(chatId);
Ребята, замечания нужны, не для красоты и не "для вида", а чтобы их **исправлять**

2024-10-30 18:07 UTC, vpyzhyanov commented on bot/src/main/java/ru/naumen/bot/data/dao/inMemory/InMemoryBalanceDao.java
> +        return usersBalance.get(chatId);
с замечанием полностью согласен, чем меньше используется null, тем меньше в программе неожиданных NPE

2024-10-30 18:15 UTC, hopenz commented on bot/src/main/java/ru/naumen/bot/data/dao/inMemory/InMemoryBalanceDao.java
> +        return usersBalance.get(chatId);
Вячеслав Юрьевич, так как Егор написал в телеграме, что это не ошибки, а просто ремарки, мы приняли к сведению  и со второй задачей хотели поправить

2024-10-30 18:31 UTC, hopenz commented
Замечания исправлены)

2024-10-30 20:46 UTC, vpyzhyanov requested changes
**Код без JavaDoc приниматься не будет!!!** В следующий раз даже смотреть не буду, сразу заверну!

Конечно вы полностью погрязли в тёмной стороне и нарушили всё, что только можно. Но в целом задача сделана довольно хорошо, видно, что старались сделать хорошо. Уверен в следующей задаче получится гораздо лучше.

2024-10-30 20:46 UTC, vpyzhyanov commented on pom.xml
> +        <module>bot</module>
Начнём со структуры проекта. Многомодульный проект состоящий из одного модуля - это вообще зачем? Не надо усложнять структуру на ровном месте. Если нет необходимости, то не надо усложнять. У вас, скорее всего, и не будет потребности в других модулях.

2024-10-30 20:46 UTC, vpyzhyanov commented on bot/.gitignore
зачем вам несколько gitignore? В этом никакого смысла нет. Вообще-то репозиторий всегда **один**, даже в многомодульном проекте.

2024-10-30 20:46 UTC, vpyzhyanov commented on bot/.gitignore
> +HELP.md
Это осознанное игнорирование? Подозреваю, что нет. Значит надо убрать

2024-10-30 20:46 UTC, vpyzhyanov commented on bot/.gitignore
> +.idea
![image](https://github.com/user-attachments/assets/8582acfa-fe13-4540-9100-c21deb0b4ab1)

(скрин из главного gitignore) Надо понимать, что игнорируя всю папку, вы игнорируете всё её содержимое

2024-10-30 20:46 UTC, vpyzhyanov commented on bot/src/main/java/ru/naumen/bot/telegramBot/controller/TgBot.java
> +public class TgBot extends TelegramBot {
Добро пожаловать на тёмную сторону. Своровали ответственность другого класса. Ещё это можно выразить так `TelegramBot  extends TelegramBot`. Если имена развернуть, то уже должно быть видно, что написано что-то не то.

На самом деле вы неправильно определили ответственность класса.

> расширяет функционал {@link TelegramBot}.

Покажите, пожалуйста, в каком конкретно месте он это делает. Я не вижу ни одного. И не надо в JavaDoc писать, что вы что-то "расширяете", слово extends и так все прекрасно видят. Пишите какую задачу выполняет класс, а не как он **реализован**.

> Он инициализируется с помощью токена, полученного из конфигурации приложения, и обрабатывает входящие обновления от Telegram, используя цепочку фильтров.

тоже пошли детали реализации. Их написать можно, ничего плохого в этом нет. Но **только после описания ответственности класса.**

Немного помогу: ответственность этого класса - настроить и запустить телеграмм бота. Ничего расширять не надо, просто создайте поле, настройте его и запустите. Назвать класс нужно соответствующе, то это будет совсем не "телеграмм бот".

2024-10-30 20:46 UTC, vpyzhyanov commented on bot/src/main/java/ru/naumen/bot/telegramBot/controller/TgBot.java
> +        super(context.getBean(ApplicationConfig.class).telegramToken());
мда.... неужели на курсе "Промышленная разработка" не учат определять и использовать бины?

2024-10-30 20:46 UTC, vpyzhyanov commented on pom.xml
> +                <artifactId>java-telegram-bot-api</artifactId>
Интересно, почему выбор пал именно на эту библиотеку, а на ту, которую предлагает сам телеграмм? https://core.telegram.org/bots/tutorial

2024-10-30 20:46 UTC, vpyzhyanov commented on bot/src/main/java/ru/naumen/bot/telegramBot/controller/TgBot.java
> +        this.setUpdatesListener(updates -> {
обычно сначала идёт настройка, а потом запуск. А не наоборот

2024-10-30 20:46 UTC, vpyzhyanov commented on bot/src/main/java/ru/naumen/bot/telegramBot/filter/chain/BotFilterChain.java
> +    private final List<ABotFilter> filters;
вот это тот самый момент, когда реально нужен интерфейс, абстрактного класса недостаточно. Если бы вы применяли ниспадающее программирование, то тут был бы интерфейс

2024-10-30 20:46 UTC, vpyzhyanov commented on bot/src/main/java/ru/naumen/bot/telegramBot/filter/chain/BotFilterChain.java
> + * Цепочка фильтров выполняется последовательно, каждый фильтр передает управление следующему.
Реально шаблон "фильтр" применили? Очень интересно как это будет работать. И что ещё более интересно как вы это дальше будете расширять.

Я удивлён, ведь для такой задачи этот паттерн неприменим. Неужели вам удалось сломать стандарты и сделать невозможное?

2024-10-30 20:46 UTC, vpyzhyanov commented on bot/src/main/java/ru/naumen/bot/telegramBot/filter/chain/BotFilterChain.java
> +    private void configureFilterChain() {
добро пожаловать на тёмную сторону. Коллективная безотстветственность. Задачу по инициализации класса вам удалось раскидать по разным местам.

PostConstruct уместен только тогда, когда вам реально нужно, чтобы весь спринг контекст был уже проинициализирован. В вашем случае - это не так. Вам можно всё сделать в конструкторе.

2024-10-30 20:46 UTC, vpyzhyanov commented on bot/src/main/java/ru/naumen/bot/telegramBot/filter/chain/BotFilterChain.java
> +            filters.get(i).setNextFilter(filters.get(i + 1));
очень интересно как вы определяете последовательность. ... Увидел, что через @Order

очень интересно как вы дальше будете расширять функционал, особенно интересно что будет, когда у вас появиться контекст. Например, одна и та же команда в разном контексте должна отрабатывать по разному или вообще не отрабатывать. Подозреваю, что вы будете решать кучу проблем, которые можно было не решать, а всё из-за того, что вы применили неправильный шаблон.

2024-10-30 20:46 UTC, vpyzhyanov commented on bot/src/main/java/ru/naumen/bot/telegramBot/filter/ABotFilter.java
> + * Абстрактный класс ABotFilter представляет собой элемент цепочки фильтров для обработки обновлений Telegram.
Не надо "воды" в описании класса. Все и так видят, что это абстрактный класс и все прекрасно видят как он называется

2024-10-30 20:46 UTC, vpyzhyanov commented on bot/src/main/java/ru/naumen/bot/telegramBot/filter/ABotFilter.java
> +import com.pengrad.telegrambot.model.Update;
не замечание, просто предупреждение. Надеюсь вы понимаете, что теперь с телеграмма вам не слезть никогда.

2024-10-30 20:46 UTC, vpyzhyanov commented on bot/src/main/java/ru/naumen/bot/telegramBot/filter/ABotFilter.java
> + * Каждый фильтр может передавать обработку следующему фильтру в цепочке, если он не завершил обработку сам.
Ну всё понятно, оказывается вы сломали сам шаблон "Фильтр", теперь это уже не фильтр, а что-то другое. То есть получается максимально запутали и себя и всю команду разработки

2024-10-30 20:46 UTC, vpyzhyanov commented on bot/src/main/java/ru/naumen/bot/telegramBot/filter/ABotFilter.java
> +public abstract class ABotFilter {
Вам приходится платить за каждый символ в коде? К чему такая экономия букв? Или название должно быть TheBotFilter?))))

`AbstractBotFilter` или `BotFilterBase`

2024-10-30 20:46 UTC, vpyzhyanov commented on bot/src/main/java/ru/naumen/bot/telegramBot/filter/ABotFilter.java
> +            nextFilter.doFilter(update);
Вот вы и попались в ловушку недоделанной абстракции. Вроде писали абстрактный класс, но он получился вообще не абстрактным. Абстрактного мышления не хватает, надо прокачивать.

А теперь по существу, в чём конкретно проблема:

- Нет никакого контракта по которому должна работать реализация `ABotFilter`
- Нужно каким-то образом догадаться, что надо переопределить метод `doFilter`.  Каким - непонятно, даже в JavaDoc это не написано.
- Если забыть переопределить метод doFilter, то просто управление перейдёт следующему фильтру и ничего не будет сделано
- Если что-то можно забыть, то это **обязательно** будет забыто
- Даже если мы не забыли переопределить метод, то нужно не забыть вызвать `getNextFilter().doFilter(update)` или `super.doFilter(update)`
- Если что-то можно забыть, то это **обязательно** будет забыто (особенно если про это **НИГДЕ** не написано)

Попробуйте сами решить это проблему и написать настоящую абстракцию, которая решит все эти проблемы. Это вам будет очень полезно. Если что я подскажу как надо, но надо обязательно попробовать самим

2024-10-30 20:46 UTC, vpyzhyanov commented on bot/src/main/java/ru/naumen/bot/telegramBot/filter/ABotFilter.java
> +    public ABotFilter getNextFilter() {
прощай инкапсуляция. А самый прикол в том, что здесь незачем приносить её в жертву. Эта жертва совершенно напрасна.

2024-10-30 20:46 UTC, vpyzhyanov commented on bot/src/main/java/ru/naumen/bot/telegramBot/filter/chain/BotFilterChain.java
> + * Цепочка фильтров выполняется последовательно, каждый фильтр передает управление следующему.
А ещё это очень неэффективное решение

2024-10-30 20:46 UTC, vpyzhyanov commented on bot/src/main/java/ru/naumen/bot/telegramBot/filter/filterImpl/CommandFilter.java
> +     * Выполняет фильтрацию обновления.
Страшная ошибка, которая полностью обесценивает полиморфизм. Переопределяя описание метода, вы полностью обесцениваете исходный интерфейс.

2024-10-30 20:46 UTC, vpyzhyanov commented on bot/src/main/java/ru/naumen/bot/telegramBot/filter/filterImpl/MessageFilter.java
> +            this.getNextFilter().doFilter(update);
дублирование кода, не находите? Какая это тёмная сторона?

2024-10-30 20:46 UTC, vpyzhyanov commented on bot/src/main/java/ru/naumen/bot/telegramBot/filter/filterImpl/StartFilter.java
> + * Класс StartFilter реализует фильтр для обработки команды "/start".
Интересно, чем же отличается команда start от всех остальных команд?

Ах да, добро пожаловать на тёмную сторону. Какую именно?

2024-10-30 20:46 UTC, vpyzhyanov commented on bot/src/main/java/ru/naumen/bot/telegramBot/filter/filterImpl/StartFilter.java
> +     * Выполняет фильтрацию обновления.
опять полиморфизм уничтожен

2024-10-30 20:46 UTC, vpyzhyanov commented on bot/src/main/java/ru/naumen/bot/telegramBot/processor/BotProcessor.java
> +public interface BotProcessor {
В тему последнего занятия, скажите пожалуйста, где используется этот интерфейс?

Добро пожаловать на тёмную сторону ООП. На какую?

2024-10-30 20:46 UTC, vpyzhyanov commented on bot/src/main/java/ru/naumen/bot/telegramBot/processor/BotProcessor.java
> +     * Метод, который должен реализовать конкретную логику обработки обновлений.
спасибо КЭП)))

2024-10-30 20:46 UTC, vpyzhyanov commented on bot/src/main/java/ru/naumen/bot/telegramBot/service/BotService.java
> +public class BotService {
Добро пожаловать в мир тёмных никому не нужных абстракций. Этот сервис просто посредник между возвращаемым сообщением и TgBot. По сути ничего ценного он не делает.

2024-10-30 20:46 UTC, vpyzhyanov commented on bot/src/main/java/ru/naumen/bot/telegramBot/service/BotService.java
> +    public void sendMessage(String message, Update update) {
А тут сервис делает то, что должен делать бот. Добро пожаловать в коллективную безотстветственность.

Отправить сообщение сам бот в состоянии и без посредников

2024-10-30 20:46 UTC, vpyzhyanov commented on bot/src/main/java/ru/naumen/bot/telegramBot/processor/impl/MessageBotProcessor.java
> +     * Добавляет доход и отправляет соответствующее собщение пользователю.
опечатка

2024-10-30 20:46 UTC, vpyzhyanov commented on bot/src/main/java/ru/naumen/bot/telegramBot/processor/impl/MessageBotProcessor.java
> +     * Добавляет расход и отправляет соответствующее собщение пользователю.
и тут

2024-10-30 20:46 UTC, vpyzhyanov commented on bot/src/main/java/ru/naumen/bot/telegramBot/processor/impl/MessageBotProcessor.java
> +     * @param update  обноление от Telegram.
и походу везде

2024-10-30 20:46 UTC, vpyzhyanov commented on bot/src/main/java/ru/naumen/bot/telegramBot/processor/impl/MessageBotProcessor.java
> +        botService.sendMessage("Расход успешно добавлен!", update);
Похоже перегруз по ответственности вы тоже не обошли стороной. Никогда бы не подумал, что метод `addExpense` будет какие-то сообщения в чат отправлять.

Методы `addExpense` и `addIncome` вообще не нужны.

2024-10-30 20:46 UTC, vpyzhyanov commented on bot/src/test/java/ru/naumen/bot/BotApplicationTests.java
> +    }
это чтобы тесты работали подольше? Поднимать весь спринговый контекст - ради чего?

2024-10-30 20:46 UTC, vpyzhyanov commented on bot/src/test/java/ru/naumen/bot/data/dao/inMemory/InMemoryBalanceDaoTest.java
> +public class InMemoryBalanceDaoTest {
код без JavaDoc приниматься не будет

2024-10-30 20:46 UTC, vpyzhyanov commented on bot/src/test/java/ru/naumen/bot/data/dao/inMemory/InMemoryBalanceDaoTest.java
> +    void testSetBalanceAndGetBalance() {
код без JavaDoc приниматься не будет

2024-10-30 20:46 UTC, vpyzhyanov commented on bot/src/test/java/ru/naumen/bot/telegramBot/command/CommandsTest.java
> +    void testGetCommands() {
смысла в тесте ноль. Он просто дублирует реализацию

2024-10-30 20:46 UTC, vpyzhyanov commented on bot/src/test/java/ru/naumen/bot/telegramBot/filter/chain/BotFilterChainTest.java
> +        method.invoke(botFilterChain);
жесть..... не ну если стремитесь максимально усложнить всем жизнь, то норм. Но если нет, то тут вы должны были задуматься а всё ли правильно вы сделали.

2024-10-30 20:46 UTC, vpyzhyanov commented on bot/src/test/java/ru/naumen/bot/telegramBot/filter/chain/BotFilterChainTest.java
> +            filter2.doFilter(invocation.getArgument(0));
тест вообще ничего не тестирует. Сами **в тесте** определили реализацию, сами её вызывали и проверили. Только смысла в этом нет

2024-10-30 20:46 UTC, vpyzhyanov commented on bot/src/test/java/ru/naumen/bot/telegramBot/filter/impl/CommandFilterTest.java
> +        update = mock(Update.class);
вот если бы не завязывались на телеграмм, то тесты были бы существенно проще. Ну ладно, сами выбрали путь без интерфейсов, пожинайте плоды

2024-10-31 13:04 UTC, LARCH1K commented on pom.xml
> +        <module>bot</module>
Проект переделан в одномодульный

2024-10-31 13:05 UTC, LARCH1K commented on bot/.gitignore
Убран вместе с дочернем модулем

2024-10-31 13:05 UTC, LARCH1K commented on bot/.gitignore
> +HELP.md
Весь файл убран

2024-10-31 13:06 UTC, LARCH1K commented on bot/.gitignore
> +.idea
Лишние строки убраны

2024-10-31 13:06 UTC, LARCH1K commented on bot/src/main/java/ru/naumen/bot/telegramBot/controller/TgBot.java
> +public class TgBot extends TelegramBot {
Исправлено на взаимодействие с TelegramBot в поле

2024-10-31 13:07 UTC, LARCH1K commented on bot/src/main/java/ru/naumen/bot/telegramBot/controller/TgBot.java
> +        super(context.getBean(ApplicationConfig.class).telegramToken());
Испралено

2024-10-31 13:08 UTC, LARCH1K commented on pom.xml
> +                <artifactId>java-telegram-bot-api</artifactId>
Данная библиотека была выбрана , так как уже был опыт работы с ней

2024-10-31 13:08 UTC, LARCH1K commented on bot/src/main/java/ru/naumen/bot/telegramBot/controller/TgBot.java
> +        this.setUpdatesListener(updates -> {
Настройка перенесена в конструктор

2024-10-31 13:11 UTC, LARCH1K commented on bot/src/main/java/ru/naumen/bot/telegramBot/filter/chain/BotFilterChain.java
> +    private final List<ABotFilter> filters;
В ходе исправления отошли от использования цепочки фильтров в пользу более простой обработки(относиться ко всем последующим замечаниям связанным с цепочкой фильтров)

2024-10-31 13:14 UTC, LARCH1K commented on bot/src/main/java/ru/naumen/bot/telegramBot/processor/BotProcessor.java
> +public interface BotProcessor {
Интерфейс убран

2024-10-31 13:16 UTC, LARCH1K commented on bot/src/main/java/ru/naumen/bot/telegramBot/processor/BotProcessor.java
> +     * Метод, который должен реализовать конкретную логику обработки обновлений.
JavaDoc убран вместе с интерфейсом

2024-10-31 13:16 UTC, LARCH1K commented on bot/src/main/java/ru/naumen/bot/telegramBot/service/BotService.java
> +public class BotService {
Класс удалён

2024-10-31 13:17 UTC, LARCH1K commented on bot/src/main/java/ru/naumen/bot/telegramBot/service/BotService.java
> +    public void sendMessage(String message, Update update) {
Метод перенесён в TelegramBotController

2024-10-31 13:17 UTC, LARCH1K commented on bot/src/main/java/ru/naumen/bot/telegramBot/processor/impl/MessageBotProcessor.java
> +     * Добавляет доход и отправляет соответствующее собщение пользователю.
Исправлено

2024-10-31 13:18 UTC, LARCH1K commented on bot/src/main/java/ru/naumen/bot/telegramBot/processor/impl/MessageBotProcessor.java
> +     * Добавляет расход и отправляет соответствующее собщение пользователю.
Исправлено

2024-10-31 13:18 UTC, LARCH1K commented on bot/src/main/java/ru/naumen/bot/telegramBot/processor/impl/MessageBotProcessor.java
> +     * @param update  обноление от Telegram.
Исправлено

2024-10-31 13:19 UTC, LARCH1K commented on bot/src/main/java/ru/naumen/bot/telegramBot/processor/impl/MessageBotProcessor.java
> +        botService.sendMessage("Расход успешно добавлен!", update);
Методы убраны, логика перенесена в processMessage()

2024-10-31 13:19 UTC, LARCH1K commented on bot/src/test/java/ru/naumen/bot/BotApplicationTests.java
> +    }
Тест удалён

2024-10-31 13:20 UTC, LARCH1K commented on bot/src/test/java/ru/naumen/bot/data/dao/inMemory/InMemoryBalanceDaoTest.java
> +public class InMemoryBalanceDaoTest {
JavaDoc ко всем тестам добавлен

2024-10-31 13:20 UTC, LARCH1K commented on bot/src/test/java/ru/naumen/bot/data/dao/inMemory/InMemoryBalanceDaoTest.java
> +    void testSetBalanceAndGetBalance() {
JavaDoc ко всем тестам добавлен

2024-10-31 13:20 UTC, LARCH1K commented on bot/src/test/java/ru/naumen/bot/telegramBot/command/CommandsTest.java
> +    void testGetCommands() {
Тест удалён

2024-10-31 13:21 UTC, LARCH1K commented on bot/src/test/java/ru/naumen/bot/telegramBot/filter/chain/BotFilterChainTest.java
> +        method.invoke(botFilterChain);
Тест удалён

2024-10-31 13:21 UTC, LARCH1K commented on bot/src/test/java/ru/naumen/bot/telegramBot/filter/chain/BotFilterChainTest.java
> +            filter2.doFilter(invocation.getArgument(0));
Тест удалён

2024-10-31 13:21 UTC, LARCH1K commented on bot/src/test/java/ru/naumen/bot/telegramBot/filter/impl/CommandFilterTest.java
> +        update = mock(Update.class);
Тест удалён

2024-10-31 13:28 UTC, LARCH1K commented
Замечания исправлены.
Основные изменения: отказались от обработки `update` в цепочке фильтров, отказались от проброса `update` до уровня сервисов (теперь `update` доходит до `updateBotProcessor`, далее взаимодействие происходит с `String message, long chatId`)

2024-10-31 14:23 UTC, YaEtoTui commented on bot/src/main/java/ru/naumen/bot/data/dao/inMemory/InMemoryBalanceDao.java
> +        return usersBalance.get(chatId);
Да, это ремарка, но лучше конечно поправить. От данной команды я услышал, что ремарка будет поправлено. 
В дальнейшем я буду писать тут, чтобы Вячеслав понимал.

2024-10-31 14:25 UTC, YaEtoTui commented
1 задача зачтена.( я забыл написать( Чтобы было в истории, напишу, что я принял работу

2024-11-12 19:16 UTC, vpyzhyanov commented on bot/src/main/java/ru/naumen/bot/data/dao/inMemory/InMemoryBalanceDao.java
> +        return usersBalance.get(chatId);
> со второй задачей хотели поправить

Зачем ждать? Если не сделаете сейчас, потом 99,9% забудете об этом. Есть такая народная мудрость "когда-то потом = никогда"

2024-11-12 19:29 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/telegramBot/command/Commands.java
> +package ru.naumen.bot.telegramBot.command;
Как команды связанные с телеграммом? Подозреваю что никак. Зачем вы тогда навязываете эту искуственную связь?

2024-11-12 19:29 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/telegramBot/command/Commands.java
> +    public BotCommand[] getCommands() {
а могли не мучаться, а сделать enum. Всё было бы в разы проще. Там даже поле с описанием можно добавить.

2024-11-12 19:29 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/telegramBot/processor/CommandBotProcessor.java
> +package ru.naumen.bot.telegramBot.processor;
Как все эти классы связанны с телеграммом? Подозреваю что никак. Зачем вы тогда навязываете эту искуственную связь?

2024-11-12 19:29 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/telegramBot/service/BalanceService.java
> +package ru.naumen.bot.telegramBot.service;
Как все эти классы связанны с телеграммом? Подозреваю что никак. Зачем вы тогда навязываете эту искуственную связь?

2024-11-12 19:29 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/telegramBot/controller/TelegramBotController.java
> +package ru.naumen.bot.telegramBot.controller;
В слове `telegramBot` слово Bot явно лишнее, т.к. оно уже в пути содержится.

Нужно стараться делать пакеты из **одного** слова. А если их несколько, то их разделять точкой.

2024-11-12 19:29 UTC, vpyzhyanov commented on bot/src/main/java/ru/naumen/bot/telegramBot/controller/TgBot.java
> +        super(context.getBean(ApplicationConfig.class).telegramToken());
В каком месте исправлено? Покажите, не вижу

![image](https://github.com/user-attachments/assets/4a628f52-1ab9-4099-b169-ae550ef6d292)

2024-11-12 19:44 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/telegramBot/controller/TelegramBotController.java
> +            updates.forEach(applicationContext.getBean(UpdateBotProcessor.class)::processUpdate);
> мда.... неужели на курсе "Промышленная разработка" не учат определять и использовать бины?

Не исправлено!

2024-11-12 19:44 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/telegramBot/controller/TelegramBotController.java
> +     * @param applicationContext контекст приложения, используемый для получения бинов
убираем это

2024-11-12 19:44 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/telegramBot/controller/TelegramBotController.java
> +    public TelegramBotController(ApplicationConfig applicationConfig, ApplicationContext applicationContext) {
Убираем ApplicationContext

2024-11-12 19:44 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/telegramBot/processor/UpdateBotProcessor.java
> +import com.pengrad.telegrambot.model.Update;
домашнее задание на построение архитектуры чат-бота должно было научить вас не делать лишние связи. Очень жаль, что не научило.

Теперь из-за этого вы уже не слезете ни с телеграмма, ни даже с этой библиотеки (мало ли она поддерживаться перестанет)

2024-11-12 19:44 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/telegramBot/processor/UpdateBotProcessor.java
> +            if (!commandBotProcessor.isChatActiveOrStarting(message, chatId)) return;
однострочное программирование - это очень дурной тон. Чтение и понимание кода это очень усложняет

2024-11-12 19:44 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/telegramBot/processor/CommandBotProcessor.java
> +        this.telegramBotController = telegramBotController;
лишняя связь с телеграммом. Необходимость в ней точно отсутствует.

Хотя в данном случае только слово Telegramm меня смущает. Больше связей с телеграммом нет.

2024-11-12 19:44 UTC, vpyzhyanov commented on bot/src/main/java/ru/naumen/bot/telegramBot/filter/ABotFilter.java
> +import com.pengrad.telegrambot.model.Update;
Видимо не понимаете, раз не слезли

2024-11-12 19:45 UTC, vpyzhyanov commented on bot/src/main/java/ru/naumen/bot/telegramBot/filter/ABotFilter.java
> +            nextFilter.doFilter(update);
пробовали?

2024-11-12 19:45 UTC, vpyzhyanov commented on bot/src/main/java/ru/naumen/bot/telegramBot/filter/filterImpl/MessageFilter.java
> +            this.getNextFilter().doFilter(update);
Нет ответа на вопрос!

2024-11-12 19:45 UTC, vpyzhyanov commented on bot/src/main/java/ru/naumen/bot/telegramBot/filter/filterImpl/StartFilter.java
> + * Класс StartFilter реализует фильтр для обработки команды "/start".
Нет ответа на вопрос!

2024-11-12 19:46 UTC, vpyzhyanov commented on bot/src/main/java/ru/naumen/bot/telegramBot/processor/BotProcessor.java
> +public interface BotProcessor {
Нет ответа на вопрос!

2024-11-12 19:51 UTC, vpyzhyanov commented on src/test/java/ru/naumen/bot/telegramBot/processor/UpdateBotProcessorTest.java
> +    private Update createUpdate(long chatId, String messageText) {
вот делать вам нечего. Сами усложнили себе жизнь. А могли без этих сложностей спокойно обойтись! Весь этот метод вообще не нужен

2024-11-12 19:51 UTC, vpyzhyanov commented on bot/src/test/java/ru/naumen/bot/telegramBot/filter/impl/CommandFilterTest.java
> +        update = mock(Update.class);
но "плоды" остались

2024-11-12 19:54 UTC, vpyzhyanov requested changes
Пока вы не начнёте отвечать на вопросы и исправлять замечания (с этим дела получше), то у вас не получится сдать задачу

2024-11-13 09:23 UTC, hopenz commented on bot/src/main/java/ru/naumen/bot/data/dao/inMemory/InMemoryBalanceDao.java
> +        return usersBalance.get(chatId);
Принято! В дальнейшем будем править сразу)
Эти ремарки уже были исправлены на момент вчерашней проверки

2024-11-13 09:24 UTC, hopenz commented on bot/src/main/java/ru/naumen/bot/configuration/ApplicationConfig.java
> +) {
Принято! В дальнейшем будем править сразу)
Эти ремарки уже были исправлены на момент вчерашней проверки

2024-11-13 09:25 UTC, LARCH1K commented on bot/src/main/java/ru/naumen/bot/telegramBot/controller/TgBot.java
> +        super(context.getBean(ApplicationConfig.class).telegramToken());
Исправили.  `ApplicationContext` оставляли для решения проблемы с циклической зависимостью. Сейчас решили проблему с использованием `@Lazy`

2024-11-13 09:26 UTC, LARCH1K commented on bot/src/main/java/ru/naumen/bot/telegramBot/filter/chain/BotFilterChain.java
> + * Цепочка фильтров выполняется последовательно, каждый фильтр передает управление следующему.
Отказались от использования фильтров

2024-11-13 09:27 UTC, LARCH1K commented on bot/src/main/java/ru/naumen/bot/telegramBot/filter/chain/BotFilterChain.java
> +    private void configureFilterChain() {
Класс удалён, в дальнейшем будем внимательнее с `@PostConstruct`

2024-11-13 09:28 UTC, LARCH1K commented on bot/src/main/java/ru/naumen/bot/telegramBot/filter/chain/BotFilterChain.java
> +            filters.get(i).setNextFilter(filters.get(i + 1));
Отказались от использования фильтров

2024-11-13 09:28 UTC, LARCH1K commented on bot/src/main/java/ru/naumen/bot/telegramBot/filter/ABotFilter.java
> + * Абстрактный класс ABotFilter представляет собой элемент цепочки фильтров для обработки обновлений Telegram.
JavaDoc удалён вместе с классом

2024-11-13 09:30 UTC, hopenz commented on bot/src/main/java/ru/naumen/bot/telegramBot/filter/ABotFilter.java
> +import com.pengrad.telegrambot.model.Update;
Вроде бы слезли, сейчас телеграмм упоминается в двух классах (`TelegramBotController` и `ApplicationConfig`)

2024-11-13 09:30 UTC, LARCH1K commented on bot/src/main/java/ru/naumen/bot/telegramBot/filter/ABotFilter.java
> + * Каждый фильтр может передавать обработку следующему фильтру в цепочке, если он не завершил обработку сам.
Отказались от использования фильтров

2024-11-13 09:34 UTC, hopenz commented on bot/src/main/java/ru/naumen/bot/telegramBot/filter/ABotFilter.java
> +public abstract class ABotFilter {
Данный класс удален, но название ABotFilter предполагало, что A - это предлог.
У нас с английским плохо видимо :)

2024-11-13 09:35 UTC, hopenz commented on bot/src/main/java/ru/naumen/bot/telegramBot/filter/ABotFilter.java
> +            nextFilter.doFilter(update);
Думали заменить абстрактный класс на интерфейс с методом doFilter, но так как решили отойти от использования фильтров применять не стали

2024-11-13 09:35 UTC, LARCH1K commented on bot/src/main/java/ru/naumen/bot/telegramBot/filter/ABotFilter.java
> +    public ABotFilter getNextFilter() {
JavaDoc удалён вместе с классом

2024-11-13 09:37 UTC, LARCH1K commented on bot/src/main/java/ru/naumen/bot/telegramBot/filter/filterImpl/CommandFilter.java
> +     * Выполняет фильтрацию обновления.
JavaDoc удалён вместе с классом

2024-11-13 09:48 UTC, hopenz commented on bot/src/main/java/ru/naumen/bot/telegramBot/filter/filterImpl/StartFilter.java
> + * Класс StartFilter реализует фильтр для обработки команды "/start".
Тут мы зашли на темную сторону "Коллективная безответственность". 
Обработка команды /start происходит так же, как и у остальных команд.

Данный класс удален.

2024-11-13 09:50 UTC, LARCH1K commented on bot/src/main/java/ru/naumen/bot/telegramBot/filter/filterImpl/MessageFilter.java
> +            this.getNextFilter().doFilter(update);
Получается сторона "Слишком много абстракций". Хотели избежать дублирования использовав абстрактный класс, но сделали только хуже.

Класс удалён

2024-11-13 09:50 UTC, hopenz commented on bot/src/main/java/ru/naumen/bot/telegramBot/filter/filterImpl/StartFilter.java
> +     * Выполняет фильтрацию обновления.
JavaDoc удалён вместе с классом

2024-11-13 09:52 UTC, hopenz commented on bot/src/main/java/ru/naumen/bot/telegramBot/processor/BotProcessor.java
> +public interface BotProcessor {
Данный интерфейс нигде не использовался.
Мы зашли на темную сторону "Слишком много абстракций" 

Класс удален

2024-11-13 09:54 UTC, hopenz commented on bot/src/test/java/ru/naumen/bot/telegramBot/filter/impl/CommandFilterTest.java
> +        update = mock(Update.class);
Максимально убрали зависимость классов от телеграмм.
Данный тест удален

2024-11-13 09:54 UTC, LARCH1K commented on src/main/java/ru/naumen/bot/telegramBot/command/Commands.java
> +package ru.naumen.bot.telegramBot.command;
Команды перенесены в отдельный пакет

2024-11-13 09:55 UTC, hopenz commented on src/main/java/ru/naumen/bot/telegramBot/command/Commands.java
> +    public BotCommand[] getCommands() {
Теперь команды перечислены в enum, где содержится их текст команды и описание

2024-11-13 09:55 UTC, LARCH1K commented on src/main/java/ru/naumen/bot/telegramBot/processor/CommandBotProcessor.java
> +package ru.naumen.bot.telegramBot.processor;
Процессоры перенесены в отдельный пакет

2024-11-13 09:55 UTC, LARCH1K commented on src/main/java/ru/naumen/bot/telegramBot/service/BalanceService.java
> +package ru.naumen.bot.telegramBot.service;
Сервисы перенесены в отдельный пакет

2024-11-13 09:56 UTC, hopenz commented on src/main/java/ru/naumen/bot/telegramBot/controller/TelegramBotController.java
> +package ru.naumen.bot.telegramBot.controller;
Принято! название пакета изменено на "telegram"

2024-11-13 09:56 UTC, LARCH1K commented on src/main/java/ru/naumen/bot/telegramBot/controller/TelegramBotController.java
> +            updates.forEach(applicationContext.getBean(UpdateBotProcessor.class)::processUpdate);
Исправили

2024-11-13 09:56 UTC, LARCH1K commented on src/main/java/ru/naumen/bot/telegramBot/controller/TelegramBotController.java
> +     * @param applicationContext контекст приложения, используемый для получения бинов
Убрали

2024-11-13 09:56 UTC, LARCH1K commented on src/main/java/ru/naumen/bot/telegramBot/controller/TelegramBotController.java
> +    public TelegramBotController(ApplicationConfig applicationConfig, ApplicationContext applicationContext) {
Убрали

2024-11-13 09:57 UTC, hopenz commented on src/main/java/ru/naumen/bot/telegramBot/processor/UpdateBotProcessor.java
> +            if (!commandBotProcessor.isChatActiveOrStarting(message, chatId)) return;
Исправили

2024-11-13 09:57 UTC, LARCH1K commented on src/main/java/ru/naumen/bot/telegramBot/processor/UpdateBotProcessor.java
> +import com.pengrad.telegrambot.model.Update;
Обработка `update` перенесена в `TelegramBotController`
Класс удалён

2024-11-13 10:00 UTC, LARCH1K commented on src/main/java/ru/naumen/bot/telegramBot/processor/CommandBotProcessor.java
> +        this.telegramBotController = telegramBotController;
`TelegramBotController` теперь имплементирует интерфейс `BotController` . В процессорах теперь взаимодействие происходит с помощью интерфейса `BotController`

2024-11-13 10:00 UTC, hopenz commented on src/test/java/ru/naumen/bot/telegramBot/processor/UpdateBotProcessorTest.java
> +    private Update createUpdate(long chatId, String messageText) {
Метод удален вместе с классом

2024-11-13 10:03 UTC, LARCH1K commented
Замечания исправили, на вопросы ответили

Основные изменения:
* Команды изменены на enum
* Логика не связанная с телеграммом вынесена в отдельные пакеты
* Обработка update перенесена в TelegramBotController
* TelegramBotController имплементирует BotController
* Процессоры используют BotController

2024-11-14 20:29 UTC, vpyzhyanov approved these changes
Процесс обучения прошёл успешно. Задача принята. Можете мёрджить

2024-11-14 20:29 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/processor/CommandBotProcessor.java
> +        Arrays.stream(Commands.values())
не надо каждый раз перебирать все команды. Просто один раз при создании положите их в подходящую для этого коллекцию

2024-11-14 20:29 UTC, vpyzhyanov commented on bot/src/main/java/ru/naumen/bot/telegramBot/filter/ABotFilter.java
> +public abstract class ABotFilter {
Предлоги в названии классов не делают

2024-11-14 20:29 UTC, vpyzhyanov commented on bot/src/main/java/ru/naumen/bot/telegramBot/filter/ABotFilter.java
> +            nextFilter.doFilter(update);
очень зря, хорошая задачка, могли бы прокачаться в работе с абстракциями

2024-11-14 20:29 UTC, vpyzhyanov commented on bot/src/main/java/ru/naumen/bot/telegramBot/filter/filterImpl/MessageFilter.java
> +            this.getNextFilter().doFilter(update);
Нет. Какая же тут абстракция? Тут конкретный класс.

Тут тёмная сторона - коллективная безответственность. Когда одно и то же делают разные классы. Отсюда и дублирование.

2024-11-14 20:29 UTC, vpyzhyanov commented on bot/src/main/java/ru/naumen/bot/telegramBot/filter/filterImpl/StartFilter.java
> + * Класс StartFilter реализует фильтр для обработки команды "/start".
Правильно

2024-11-14 20:29 UTC, vpyzhyanov commented on bot/src/main/java/ru/naumen/bot/telegramBot/processor/BotProcessor.java
> +public interface BotProcessor {
правильно

2024-11-14 20:31 UTC, vpyzhyanov commented
Оценка 

- ООП: 5 из 5
- Git 3 из 3

2024-11-14 20:55 UTC, merged

2024-11-15 03:02 UTC, LARCH1K commented on src/main/java/ru/naumen/bot/processor/CommandBotProcessor.java
> +        Arrays.stream(Commands.values())
Исправили, теперь при запуске приложения команды записываются в Map и в методе достаются по ключу, где ключ строковый текст команды